# Generated by Django 5.0.1 on 2024-01-30 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_remove_rent_is_rented'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='iha_id',
            new_name='iha',
        ),
        migrations.RenameField(
            model_name='rent',
            old_name='user_id',
            new_name='user',
        ),
    ]
