# Generated by Django 5.0.1 on 2024-01-30 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_rename_iha_rent_iha_id_rename_user_rent_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='iha_id',
            new_name='iha',
        ),
        migrations.RenameField(
            model_name='rent',
            old_name='user_id',
            new_name='user',
        ),
    ]
