# Generated by Django 5.0.1 on 2024-01-30 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_rename_iha_id_rent_iha_rename_user_id_rent_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rent',
            old_name='iha',
            new_name='iha_id',
        ),
        migrations.RenameField(
            model_name='rent',
            old_name='user',
            new_name='user_id',
        ),
    ]
