# Generated by Django 5.0.1 on 2024-01-30 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_alter_rent_iha_id_alter_rent_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='iha_id',
            field=models.ForeignKey(db_column='iha_id', on_delete=django.db.models.deletion.CASCADE, to='database.iha'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='user_id',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='database.user'),
        ),
    ]
